import React, { createContext, useContext, useState, useCallback } from "react";

const translations = {
    tr: {
        // ── Common ─────────────────────────────────────────────
        close: "Kapat",
        cancel: "İptal",
        save: "Kaydet",
        standard: "Standart",
        'cat.device_upgrade': "Cihaz Yükseltme",
        'cat.standby_reduction': "Bekleme Tüketimi",
        'cat.usage_optimization': "Kullanım Optimizasyonu",
        add: "Ekle",
        back: "Geri",
        loading: "Yükleniyor…",
        delete: "Sil",
        edit: "Düzenle",
        create: "Oluştur",
        or: "veya",
        days: "gün",
        result: "sonuç",

        // ── Auth ───────────────────────────────────────────────
        login: "Giriş",
        register: "Kayıt Ol",
        logout: "Çıkış Yap",
        defaultUser: "Kullanıcı",

        // ── Navigation / Dashboard ─────────────────────────────
        dashboard: "Panel",
        settings: "Ayarlar",
        support: "Destek Merkezi",
        supportCenter: "Destek ve Bildirim Merkezi",
        goBack: "Geri Dön",

        // Tabs
        tabOverview: "Özet",
        tabSuggestions: "Öneriler",
        tabRanking: "Sıralama",
        tabBills: "Faturalar",
        tabOverviewShort: "Ö",
        tabSuggestionsShort: "İ",
        tabRankingShort: "S",
        tabBillsShort: "F",
        expandPanel: "Paneli aç",
        collapsePanel: "Paneli küçült",

        // ── Devices ────────────────────────────────────────────
        addDevice: "Cihaz Ekle",
        selectNewDevice: "Yeni Cihaz Seç",
        selectDevice: "Cihaz Seç",
        deviceDetail: "Cihaz Detayı",
        deleteDevice: "Cihazı Sil (Del)",
        deviceConsumption: "Cihaz Tüketimi",
        selectedLabel: "Seçili",
        pickModel: "Bir model seçin",
        searchModel: "Model ara…",
        noResults: "Sonuç bulunamadı",
        category: "Kategori",
        alreadyAdded: "Eklendi",
        hPerDay: "saat/gün",
        hPerMonth: "saat/ay",
        usageSetting: "Kullanım Ayarı",
        weeklyUsageCycles: "Haftalık kullanım (kez)",
        dailyUsageHours: "Günlük kullanım (saat)",
        energyCalcNote: "enerji hesabı için",
        fridgeAlwaysOn: "Buzdolabı her zaman açıktır",
        calculatingML: "ML hesaplanıyor…",
        mlBackendError: "ML backend bağlanamadı. Gerçek veri yok.",
        theoretical: "Teorik",
        actual: "Gerçek",

        // Device type labels
        "device.fridge": "Buzdolabı",
        "device.tv": "Televizyon",
        "device.ac": "Klima",
        "device.washing_machine": "Çamaşır Mak.",
        "device.dishwasher": "Bulaşık Mak.",
        "device.oven": "Fırın",
        "device.computer": "Bilgisayar",
        "device.lighting": "Aydınlatma",
        "device.water_heater": "Su Isıtıcı",
        "device.dryer": "Kurutma Mak.",

        // Device profile names (catalog)
        "profile.fridge": "Standart Buzdolabı",
        "profile.tv": "Standart TV",
        "profile.ac": "Standart Klima",
        "profile.washing_machine": "Standart Çamaşır Mak.",
        "profile.dishwasher": "Standart Bulaşık Mak.",
        "profile.oven": "Standart Fırın",
        "profile.computer": "Standart Bilgisayar",
        "profile.lighting": "Standart Aydınlatma",
        "profile.water_heater": "Standart Şofben",
        "profile.dryer": "Standart Kurutma Mak.",

        // ── Rooms ──────────────────────────────────────────────
        addRoom: "Oda Ekle",
        addNewRoom: "+ Yeni Oda Ekle",
        deleteRoom: "Odayı Sil",
        deleteSelected: "Seçiliyi Sil (Del)",
        createNewRoom: "Yeni Oda Oluştur",
        roomName: "Oda Adı",
        roomType: "Oda Tipi",
        dimensions: "Boyutlar",
        dimensionsExample: "Örn: 4m × 5m oda → 4 genişlik, 5 uzunluk",
        width: "Genişlik",
        depth: "Uzunluk",
        height: "Yükseklik",
        addRoomFirst: "Lütfen önce bir oda ekleyin!",
        loadingHome: "Eviniz yükleniyor…",
        preparingHome: "Eviniz hazırlanıyor…",
        exampleRoomName: "Örn: Ana Yatak Odası",

        // Room types
        "room.kitchen": "Mutfak",
        "room.living": "Oturma Odası",
        "room.bedroom": "Yatak Odası",
        "room.bathroom": "Banyo",
        "room.laundry": "Çamaşır Odası",
        "room.office": "Ofis",
        "room.hallway": "Koridor",
        "room.general": "Genel",

        // Room type hints
        "roomHint.kitchen": "Buzdolabı, fırın, bulaşık makinesi önerilir",
        "roomHint.living": "TV, klima önerilir",
        "roomHint.bedroom": "Klima, bilgisayar önerilir",
        "roomHint.bathroom": "Su ısıtıcı önerilir",
        "roomHint.laundry": "Çamaşır & kurutma makinesi önerilir",
        "roomHint.office": "Bilgisayar, aydınlatma önerilir",
        "roomHint.general": "Özel öneri yok",

        // ── Energy & Consumption ───────────────────────────────
        consumption: "Aylık Tüketim Durumu",
        monthlyConsumptionStatus: "Aylık Tüketim Durumu",
        kwh: "KWH",
        kwhPerMonth: "kWh/ay",
        estimatedBill: "Tahmini Fatura",
        seeDetails: "Detayları Gör",
        efficiency: "Verimlilik",
        efficiencyScore: "Verimlilik Skoru",
        topExpenses: "En Çok Harcayanlar",
        billAvg: "Fatura ort.",
        turkeyAvg: "Türkiye ort.",

        // ── Bills ──────────────────────────────────────────────
        billsTitle: "Faturalar",
        addBill: "+ Yeni Fatura Ekle",
        deleteBill: "Faturayı sil",
        billsAvgLabel: "Son {n} faturanın ortalaması",
        averageRate: "Ortalama birim",
        noBillsYet: "Henüz fatura eklenmemiş.",
        noBillsDesc: "Tahmini değerler yerine gerçek fatura verilerinizi kullanmak için fatura ekleyin.",
        fromBill: "Faturadan",
        estimated: "Tahmin",
        dataLoadError: "Veriler yüklenemedi. Lütfen sayfayı yenileyin.",

        // ── Suggestions / Recommendations ──────────────────────
        recommendations: "AI Önerileri",
        savingsSuggestions: "Tasarruf Önerileri",
        suggestion: "Öneri",
        energySavingSuggestion: "Enerji tasarrufu önerisi",
        savingsPerMonth: "tasarruf",
        noSuggestionsYet: "Henüz öneri yok.",
        noSuggestionsDesc: "Cihaz ekledikten sonra AI öneriler üretecek.",

        // ── Peer Comparison (HomeRanking) ──────────────────────
        peerComparison: "Komşu Karşılaştırması",
        householdRanking: "Hanehalkı Sıralaması",
        noComparisonData: "Henüz karşılaştırma verisi yok.",
        noComparisonDesc: "Bir cihaz ekleyin veya bir fatura kaydedin.",
        rankingFailed: "Sıralama hesaplanamadı.",
        rankingFailedDesc: "ML servisinin çalıştığından emin olun.",
        homeInCluster: "Eviniz benzer {n} hane içinde",
        usesLessEnergy: "'inden daha az enerji kullanıyor",
        lowConsumption: "Az tüketim",
        highConsumption: "Çok tüketim",
        me: "Ben",
        you: "Sen",
        average: "Ortalama",
        difference: "Fark",
        belowAverage: "Ortalamanın altında",
        atAverage: "Ortalamada",
        aboveAverage: "Ortalamanın üstünde",
        basedOnBill: "Faturanıza göre",
        basedOnPrediction: "Tahmine göre",

        // ── Goals (StreakCard) ──────────────────────────────────
        monthlyGoal: "Aylık Hedef",
        setGoal: "Hedef Belirle",
        setGoalDesc: "Bu ay için bir tüketim hedefi belirleyin — sayılar ilerledikçe sizi haberdar edelim.",
        editGoal: "Hedefi düzenle",
        removeGoal: "Hedefi kaldır",
        kwhGoal: "kWh hedef",
        loadingGoal: "Hedef yükleniyor…",
        invalidGoal: "Geçerli bir hedef girin (kWh).",
        goalSaveError: "Hedef kaydedilemedi.",
        goalSaved: "Aylık hedef kaydedildi.",
        goalDeleteError: "Hedef silinemedi.",
        goalDeleted: "Hedef kaldırıldı.",
        onTrack: "Hedef yolunda",
        tight: "Sınırda",
        over: "Hedef aşılıyor",
        projectedMonthEnd: "Tahmini ay sonu",
        goalPeriod: "Hedef dönemi",
        fromLastBill: "son faturanızdan",
        calendarMonth: "takvim ayı",
        typicalConsumption: "göre tipik tüketim",
        completed: "yoldasınız",
        noProjectionYet: "Cihaz veya fatura ekleyince ay sonu tahmini görünecek.",
        bill: "fatura",
        simulation: "simülasyon",
        basedOnBillGoal: "Faturanıza",
        basedOnSimGoal: "Simülasyona",

        // ── Home Builder Wizard ────────────────────────────────
        setupHome: "Evinizi Kurun",
        customDesign: "Özel Tasarım",
        customDesignDesc: "Oda ekleyin, isimlendirin, cihazları seçin — tamamen size özel bir ev oluşturun.",
        selectOrCustom: "Hazır şablonlardan seçin veya kendiniz tasarlayın",
        designRooms: "Odaları ve cihazları kendiniz belirleyin",
        settingUpHome: "Eviniz kuruluyor...",
        addingRoomsDevices: "Odalar ve cihazlar ekleniyor",
        rooms: "Odalar",
        devices: "Cihazlar",
        buildHome: "Evi Kur",
        "preset.small": "Küçük Ev",
        "preset.smallDesc": "Tek kişilik veya çift yaşama uygun, kompakt bir ev.",
        "preset.medium": "Orta Ev",
        "preset.mediumDesc": "Aileler için ideal, geniş yaşam alanı.",
        "preset.large": "Büyük Ev",
        "preset.largeDesc": "Geniş aile veya ev ofisi için, tüm olanaklar.",
        describeHome: "Evimi Anlat",
        describeHomeDesc: "Evinizi tarif edin — AI otomatik olarak oda ve cihazlarınızı eklesin.",
        start: "Başla",

        // ── AI Assistant ───────────────────────────────────────
        kwhaneAi: "KWhane AI",
        aiOnline: "Yapay Zeka Çevrimiçi",
        aiRecommendationEx: "Buzdolabınız standartların <strong>%25</strong> üzerinde enerji harcıyor. A+++ model ile ayda 120₺ tasarruf edilebilir.",

        // ── Scene ──────────────────────────────────────────────
        loadingScene: "Sahne yükleniyor…",
        previewPlaceholder: "Bir model seçince tahmin yüklenecek.",
        searchCatalog: "Cihaz katalogunda ara…",
        seeAll: "Tümünü gör",

        // ── Profile / Settings ─────────────────────────────────
        overview: "Genel Bakış",
        profileSettings: "Profil Ayarları",
        accountInfo: "Hesap Bilgileri",
        changeEmail: "E-posta Değiştir",
        updateEmail: "E-posta Güncelle",
        newEmail: "Yeni E-posta Adresi",
        currentPassword: "Mevcut Şifre",
        changePassword: "Şifre Değiştir",
        newPassword: "Yeni Şifre",
        newPasswordConfirm: "Yeni Şifre (Tekrar)",
        updatePassword: "Şifreyi Güncelle",
        systemSettings: "Sistem Ayarları",
        unitsAndRegion: "Birimler ve Bölge",
        defaultTariff: "Varsayılan Tarife",
        dataPrivacy: "Veri Gizliliği",
        performance: "Performans",
        deviceIntegration: "Cihaz Entegrasyonu",
        unitsDesc: "Uygulama genelinde kullanılacak ölçü birimleri ve bölgesel ayarlar.",
        energyUnit: "Enerji Birimi",
        currency: "Para Birimi",
        timezone: "Zaman Dilimi",
        dateFormat: "Tarih Formatı",
        saveChanges: "Değişiklikleri Kaydet",

        // Settings sections
        homeProfile: "Ev Profili",
        homeProfileDesc: "Evinizin temel bilgilerini düzenleyin.",
        city: "Şehir",
        occupants: "Sakin Sayısı",
        squareMeters: "Metrekare (m²)",
        tariffInfo: "Tarife Bilgisi",
        tariffInfoDesc: "Güncel elektrik tarife kademelerini görüntüleyin.",
        noTariffData: "Tarife verisi bulunamadı...",
        tier: "Kademe",
        notifications: "Bildirimler",
        notificationsDesc: "Hangi bildirimleri almak istediğinizi seçin.",
        weeklyEmailDigest: "Haftalık e-posta özeti",
        weeklyEmailDesc: "Her Pazartesi tüketim özetinizi alın.",
        savingsAlerts: "Tasarruf uyarıları",
        savingsAlertsDesc: "Anomali veya yüksek tüketim bildirimleri.",
        deviceRecommendations: "Cihaz önerileri",
        deviceRecommendationsDesc: "Yapay zeka destekli ürün tavsiyeleri.",
        appearance: "Görünüm",
        appearanceDesc: "Tema ve simülasyon kalite ayarları.",
        theme: "Tema",
        dark: "Koyu",
        light: "Açık",
        simulationQuality: "3D Simülasyon Kalitesi",
        low: "Düşük",
        medium: "Orta",
        high: "Yüksek",

        // ── Theme toggle ───────────────────────────────────────
        darkTheme: "Koyu Tema",
        lightTheme: "Açık Tema",
        changeLanguage: "Dili Değiştir",

        // ── Calibration ────────────────────────────────────────
        calibrationWarning: "İlerleme simülasyona göre hesaplanıyor — gerçek tüketimle uyum için",
        calibrationAction: "Faturalar sekmesinden kalibrasyon önerilerini uygulayın.",

        // ── Extra keys ─────────────────────────────────────────
        less: "az",
        more: "fazla",
        higher: "yüksek",
        lower: "düşük",
        device: "Cihaz",
        trendCompare: "{label}'ndan {pct}% {dir}",
        efficiencyShort: "Verim",
        weekly: "Haftalık",
        daily: "Günlük",
        times: "sefer",
        hours: "saat",
        homeConsumptionLabel: "Eviniz {label} tüketim yapıyor",
        calibrationGapPrefix: "Simülasyonunuz ({sim} kWh) son faturanızdan ({bill} kWh)",
        analyzingHome: "Eviniz analiz ediliyor…",
        aiWelcomeBills: "Son {n} faturanıza göre ortalama ₺{cost}/ay ({kwh} kWh) ödüyorsunuz. Nereyi konuşalım?",
        aiWelcomeNoDevices: "Henüz cihaz eklenmemiş. Sol panelden bir cihaz ekledikten sonra enerji analizinizi yapabilirim.",
        aiWelcomeDevices: "Evinizde {n} cihaz var, toplam {kwh} kWh/ay, ₺{cost}/ay tahmini maliyet. Ne öğrenmek istersiniz?",
        aiWelcomeDevicesNoCost: "Evinizde {n} cihaz eklenmiş. Enerji hesaplamaları tamamlandığında size daha detaylı bilgi verebilirim. Ne sormak istersiniz?",
        openAiAssistant: "KWhane AI yardımcısını aç",
        askSomething: "Bir şey sor… (Enter ile gönder)",
        stopMic: "Mikrofonu durdur",
        voiceInput: "Sesle yaz",
        poweredBy: "Llama 3.2 (Ollama) ile desteklenmektedir",
        aiConnectionError: "AI servisine bağlanılamadı. Backend'in çalıştığını ve OPENAI_API_KEY'in ayarlandığını kontrol edin.",
        account: "Hesap",
        accountDesc: "Hesap bilgileri ve tehlikeli eylemler.",
        emailLabel: "E-posta",
        profileLoadError: "Profil yüklenemedi.",
        saveFailed: "Kaydedilemedi",
        savingText: "Kaydediliyor...",
        savedText: "Kaydedildi!",
        dangerZone: "Tehlikeli Alan",
        dangerZoneDesc: "Tüm oda ve cihaz verileriniz silinir. Bu işlem geri alınamaz.",
        resetHomeData: "Tüm ev verisini sıfırla",
        yesDelete: "Evet, sil",
        resetFailed: "Sıfırlama başarısız",
        mlConnectionFailed: "ML bağlanamadı",
        calculating: "Hesaplanıyor…",
        vatRate: "KDV",
        fillTariffTable: "Tarife verisi bulunamadı. Supabase'de electricity_tariffs tablosunu doldurun.",

        // ── Calibration Card ───────────────────────────────────
        calibrating: "Tahminler kalibre ediliyor…",
        predictionsMatch: "Tahminler faturanızla uyumlu",
        predictionsWithin: "Son {n} faturanın ortalaması ({actual} kWh) ile tahminimiz ({predicted} kWh) %5 içinde.",
        predictionsVsBill: "Tahminler vs Fatura",
        predVsBillStat: "Son {n} faturada gerçek tüketim {actual} kWh, tahminimiz {predicted} kWh",
        addHourDeviceHint: "Aydınlatma, klima gibi saat-tabanlı bir cihaz ekleyince burada öneriler gösterebiliriz.",
        calibrationSaveFailed: "Kalibrasyon kaydedilemedi.",
        calibrationUpdated: "{name}: {from}s → {to}s olarak güncellendi.",
        predictionCalibration: "Tahmin Kalibrasyonu",
        calSentence1: "Son {n} faturada tahminlerimiz ortalama",
        calSentence2: "çıktı ({actual} kWh gerçek vs {predicted} kWh tahmini).",
        calSuggestIncrease: "Beyan ettiğiniz saatleri biraz artırarak tahminleri faturaya yaklaştırabiliriz.",
        calSuggestDecrease: "Beyan ettiğiniz saatleri biraz azaltarak tahminleri faturaya yaklaştırabiliriz.",
        hDay: "s/gün",
        applied: "Uygulandı",
        applying: "Uygulanıyor…",
        apply: "Uygula",
        calDisclaimer: "Onayınız olmadan değişiklik yapılmaz. Orijinal değerleriniz kayıt altında tutulur.",

        // ── Bill Entry Modal ───────────────────────────────────
        billSaved: "Fatura Kaydedildi",
        addBillTitle: "Fatura Ekle",
        billEntryDesc: "Son elektrik faturanızı girin. Bu sayede tahminler yerine gerçek tüketiminize dayalı öneriler verebiliriz.",
        periodStart: "Dönem Başlangıcı",
        periodEnd: "Dönem Bitişi",
        totalConsumption: "Toplam Tüketim",
        totalAmount: "Toplam Tutar",
        providerLabel: "Sağlayıcı",
        optional: "opsiyonel",
        avgUnitPrice: "Ortalama birim fiyat",
        duplicateBill: "Bu döneme ait fatura zaten kayıtlı.",
        billSaveFailed: "Fatura kaydedilemedi. Lütfen tekrar deneyin.",

        // ── Bill Diagnostic Card ───────────────────────────────
        analyzingBill: "Faturanız analiz ediliyor…",
        billSavedNoAnalysis: "Fatura kaydedildi, ancak analiz şu an yapılamıyor.",
        ensureMlRunning: "ML servisinin çalıştığından emin olun.",
        billAnalysis: "Fatura Analizi",
        matchesPrediction: "Tahminle uyumlu",
        higherThanPred: "Tahminden %{pct} yüksek",
        lowerThanPred: "Tahminden %{pct} düşük",
        consumptionBreakdown: "Tüketim Dağılımı",
        total: "Toplam",
        findings: "Tespit Ettiklerimiz",
        noDevicesAnalyzed: "Cihazlar henüz analiz edilmedi.",
        noDevicesAnalyzedDesc: "Cihaz ekleyip enerji hesaplaması tamamlandığında, bu fatura için detaylı analiz oluşturabiliriz.",
        ok: "Tamam",
        addThisDevice: "Bu cihazı ekle",
        updateHours: "Saatleri güncelle",
        updateYear: "Yılını düzelt",
        verifyClass: "Sınıfı kontrol et",
        updateTariff: "Tarifeyi güncelle",
        hoursUpdatedTo: "Kullanım saati {h} saat olarak güncellendi.",
        yearUpdatedTo: "Cihaz yılı {y} olarak güncellendi. Doğru yılı Cihazlar sekmesinden de düzenleyebilirsiniz.",
        addFromCatalog: "Cihaz katalogundan ekleyin: sol panel → Cihaz Ekle.",
        verifyClassHint: "Cihazlar sekmesinden verim sınıfını gözden geçirin.",
        tariffOverrideSoon: "Tarife geçersiz kılma yakında geliyor — şimdilik tahminler bilgilendirme amaçlı.",
        actionFailed: "İşlem başarısız oldu.",
    },
    en: {
        // ── Common ─────────────────────────────────────────────
        close: "Close",
        cancel: "Cancel",
        save: "Save",
        standard: "Standard",
        'cat.device_upgrade': "Device Upgrade",
        'cat.standby_reduction': "Standby Consumption",
        'cat.usage_optimization': "Usage Optimization",
        add: "Add",
        back: "Back",
        loading: "Loading…",
        delete: "Delete",
        edit: "Edit",
        create: "Create",
        or: "or",
        days: "days",
        result: "results",

        // ── Auth ───────────────────────────────────────────────
        login: "Login",
        register: "Register",
        logout: "Logout",
        defaultUser: "User",

        // ── Navigation / Dashboard ─────────────────────────────
        dashboard: "Dashboard",
        settings: "Settings",
        support: "Support Center",
        supportCenter: "Support & Ticket Center",
        goBack: "Go Back",

        // Tabs
        tabOverview: "Overview",
        tabSuggestions: "Suggestions",
        tabRanking: "Ranking",
        tabBills: "Bills",
        tabOverviewShort: "O",
        tabSuggestionsShort: "S",
        tabRankingShort: "R",
        tabBillsShort: "B",
        expandPanel: "Expand panel",
        collapsePanel: "Collapse panel",

        // ── Devices ────────────────────────────────────────────
        addDevice: "Add Device",
        selectNewDevice: "Select New Device",
        selectDevice: "Select Device",
        deviceDetail: "Device Detail",
        deleteDevice: "Delete Device (Del)",
        deviceConsumption: "Device Consumption",
        selectedLabel: "Selected",
        pickModel: "Pick a model",
        searchModel: "Search model…",
        noResults: "No results found",
        category: "Category",
        alreadyAdded: "Added",
        hPerDay: "h/day",
        hPerMonth: "h/month",
        usageSetting: "Usage Setting",
        weeklyUsageCycles: "Weekly usage (cycles)",
        dailyUsageHours: "Daily usage (hours)",
        energyCalcNote: "for energy calculation",
        fridgeAlwaysOn: "Fridge is always on",
        calculatingML: "Calculating…",
        mlBackendError: "ML backend unreachable. No real data.",
        theoretical: "Theoretical",
        actual: "Actual",

        // Device type labels
        "device.fridge": "Fridge",
        "device.tv": "Television",
        "device.ac": "Air Conditioner",
        "device.washing_machine": "Washing Mach.",
        "device.dishwasher": "Dishwasher",
        "device.oven": "Oven",
        "device.computer": "Computer",
        "device.lighting": "Lighting",
        "device.water_heater": "Water Heater",
        "device.dryer": "Dryer",

        // Device profile names (catalog)
        "profile.fridge": "Standard Fridge",
        "profile.tv": "Standard TV",
        "profile.ac": "Standard AC",
        "profile.washing_machine": "Standard Washing Mach.",
        "profile.dishwasher": "Standard Dishwasher",
        "profile.oven": "Standard Oven",
        "profile.computer": "Standard Computer",
        "profile.lighting": "Standard Lighting",
        "profile.water_heater": "Standard Water Heater",
        "profile.dryer": "Standard Dryer",

        // ── Rooms ──────────────────────────────────────────────
        addRoom: "Add Room",
        addNewRoom: "+ Add New Room",
        deleteRoom: "Delete Room",
        deleteSelected: "Delete Selected (Del)",
        createNewRoom: "Create New Room",
        roomName: "Room Name",
        roomType: "Room Type",
        dimensions: "Dimensions",
        dimensionsExample: "E.g.: 4m × 5m room → 4 width, 5 depth",
        width: "Width",
        depth: "Depth",
        height: "Height",
        addRoomFirst: "Please add a room first!",
        loadingHome: "Loading your home…",
        preparingHome: "Preparing your home…",
        exampleRoomName: "E.g.: Master Bedroom",

        // Room types
        "room.kitchen": "Kitchen",
        "room.living": "Living Room",
        "room.bedroom": "Bedroom",
        "room.bathroom": "Bathroom",
        "room.laundry": "Laundry Room",
        "room.office": "Office",
        "room.hallway": "Hallway",
        "room.general": "General",

        // Room type hints
        "roomHint.kitchen": "Fridge, oven, dishwasher recommended",
        "roomHint.living": "TV, air conditioner recommended",
        "roomHint.bedroom": "AC, computer recommended",
        "roomHint.bathroom": "Water heater recommended",
        "roomHint.laundry": "Washer & dryer recommended",
        "roomHint.office": "Computer, lighting recommended",
        "roomHint.general": "No specific recommendations",

        // ── Energy & Consumption ───────────────────────────────
        consumption: "Monthly Consumption",
        monthlyConsumptionStatus: "Monthly Consumption",
        kwh: "KWH",
        kwhPerMonth: "kWh/mo",
        estimatedBill: "Estimated Bill",
        seeDetails: "See Details",
        efficiency: "Efficiency",
        efficiencyScore: "Efficiency Score",
        topExpenses: "Top Expenses",
        billAvg: "Bill avg.",
        turkeyAvg: "Turkey avg.",

        // ── Bills ──────────────────────────────────────────────
        billsTitle: "Bills",
        addBill: "+ Add New Bill",
        deleteBill: "Delete bill",
        billsAvgLabel: "Average of last {n} bills",
        averageRate: "Average rate",
        noBillsYet: "No bills added yet.",
        noBillsDesc: "Add a bill to use real data instead of estimates.",
        fromBill: "From bill",
        estimated: "Estimated",
        dataLoadError: "Data couldn't be loaded. Please refresh the page.",

        // ── Suggestions / Recommendations ──────────────────────
        recommendations: "AI Recommendations",
        savingsSuggestions: "Savings Suggestions",
        suggestion: "Suggestion",
        energySavingSuggestion: "Energy saving suggestion",
        savingsPerMonth: "savings",
        noSuggestionsYet: "No suggestions yet.",
        noSuggestionsDesc: "AI will generate suggestions after you add a device.",

        // ── Peer Comparison (HomeRanking) ──────────────────────
        peerComparison: "Peer Comparison",
        householdRanking: "Household Ranking",
        noComparisonData: "No comparison data yet.",
        noComparisonDesc: "Add a device or enter a bill.",
        rankingFailed: "Ranking couldn't be calculated.",
        rankingFailedDesc: "Make sure the ML service is running.",
        homeInCluster: "Your home among {n} similar households",
        usesLessEnergy: "uses less energy than",
        lowConsumption: "Low consumption",
        highConsumption: "High consumption",
        me: "Me",
        you: "You",
        average: "Average",
        difference: "Diff.",
        belowAverage: "Below average",
        atAverage: "Average",
        aboveAverage: "Above average",
        basedOnBill: "Based on your bill",
        basedOnPrediction: "Based on prediction",

        // ── Goals (StreakCard) ──────────────────────────────────
        monthlyGoal: "Monthly Goal",
        setGoal: "Set Goal",
        setGoalDesc: "Set a consumption goal for this month — we'll keep you posted as numbers progress.",
        editGoal: "Edit goal",
        removeGoal: "Remove goal",
        kwhGoal: "kWh goal",
        loadingGoal: "Loading goal…",
        invalidGoal: "Enter a valid goal (kWh).",
        goalSaveError: "Goal couldn't be saved.",
        goalSaved: "Monthly goal saved.",
        goalDeleteError: "Goal couldn't be deleted.",
        goalDeleted: "Goal removed.",
        onTrack: "On track",
        tight: "Tight",
        over: "Over target",
        projectedMonthEnd: "Projected month-end",
        goalPeriod: "Goal period",
        fromLastBill: "from your last bill",
        calendarMonth: "calendar month",
        typicalConsumption: "typical consumption based on",
        completed: "completed",
        noProjectionYet: "Add a device or bill to see month-end projection.",
        bill: "bill",
        simulation: "simulation",
        basedOnBillGoal: "Your bill",
        basedOnSimGoal: "Simulation",

        // ── Home Builder Wizard ────────────────────────────────
        setupHome: "Set Up Your Home",
        customDesign: "Custom Design",
        customDesignDesc: "Add rooms, name them, pick devices — create a fully custom home.",
        selectOrCustom: "Pick a template or design your own",
        designRooms: "Define rooms and devices yourself",
        settingUpHome: "Setting up your home...",
        addingRoomsDevices: "Adding rooms and devices",
        rooms: "Rooms",
        devices: "Devices",
        buildHome: "Build Home",
        "preset.small": "Small Home",
        "preset.smallDesc": "Compact home for one or two people.",
        "preset.medium": "Medium Home",
        "preset.mediumDesc": "Ideal for families, spacious living area.",
        "preset.large": "Large Home",
        "preset.largeDesc": "For large families or home offices, all amenities.",
        describeHome: "Describe My Home",
        describeHomeDesc: "Describe your home — AI will automatically add rooms and devices.",
        start: "Start",

        // ── AI Assistant ───────────────────────────────────────
        kwhaneAi: "KWhane AI",
        aiOnline: "AI Online",
        aiRecommendationEx: "Your fridge uses <strong>25%</strong> more energy than average. Switching to an A+++ model could save ₺120/month.",

        // ── Scene ──────────────────────────────────────────────
        loadingScene: "Loading scene…",
        previewPlaceholder: "Predictions will load once you pick a model.",
        searchCatalog: "Search the device catalog…",
        seeAll: "See all",

        // ── Profile / Settings ─────────────────────────────────
        overview: "Overview",
        profileSettings: "Profile Settings",
        accountInfo: "Account Info",
        changeEmail: "Change Email",
        updateEmail: "Update Email",
        newEmail: "New Email Address",
        currentPassword: "Current Password",
        changePassword: "Change Password",
        newPassword: "New Password",
        newPasswordConfirm: "New Password (Confirm)",
        updatePassword: "Update Password",
        systemSettings: "System Settings",
        unitsAndRegion: "Units & Region",
        defaultTariff: "Default Tariff",
        dataPrivacy: "Data Privacy",
        performance: "Performance",
        deviceIntegration: "Device Integration",
        unitsDesc: "Unit and regional settings used throughout the application.",
        energyUnit: "Energy Unit",
        currency: "Currency",
        timezone: "Timezone",
        dateFormat: "Date Format",
        saveChanges: "Save Changes",

        // Settings sections
        homeProfile: "Home Profile",
        homeProfileDesc: "Edit your home's basic info.",
        city: "City",
        occupants: "Occupants",
        squareMeters: "Square Meters (m²)",
        tariffInfo: "Tariff Info",
        tariffInfoDesc: "View current electricity tariff tiers.",
        noTariffData: "No tariff data found...",
        tier: "Tier",
        notifications: "Notifications",
        notificationsDesc: "Choose which notifications you'd like to receive.",
        weeklyEmailDigest: "Weekly email digest",
        weeklyEmailDesc: "Get your consumption summary every Monday.",
        savingsAlerts: "Savings alerts",
        savingsAlertsDesc: "Anomaly or high consumption notifications.",
        deviceRecommendations: "Device recommendations",
        deviceRecommendationsDesc: "AI-powered product suggestions.",
        appearance: "Appearance",
        appearanceDesc: "Theme and simulation quality settings.",
        theme: "Theme",
        dark: "Dark",
        light: "Light",
        simulationQuality: "3D Simulation Quality",
        low: "Low",
        medium: "Medium",
        high: "High",

        // ── Theme toggle ───────────────────────────────────────
        darkTheme: "Dark Theme",
        lightTheme: "Light Theme",
        changeLanguage: "Change Language",

        // ── Calibration ────────────────────────────────────────
        calibrationWarning: "Progress is based on simulation — for real-world accuracy,",
        calibrationAction: "apply calibration suggestions from the Bills tab.",

        // ── Extra keys ─────────────────────────────────────────
        less: "less",
        more: "more",
        higher: "higher",
        lower: "lower",
        device: "Device",
        trendCompare: "{pct}% {dir} than {label}",
        efficiencyShort: "Eff.",
        weekly: "Weekly",
        daily: "Daily",
        times: "times",
        hours: "hours",
        homeConsumptionLabel: "Your home's consumption is {label}",
        calibrationGapPrefix: "Your simulation ({sim} kWh) vs. your last bill ({bill} kWh):",
        analyzingHome: "Analyzing your home…",
        aiWelcomeBills: "Based on your last {n} bills, you pay about ₺{cost}/mo ({kwh} kWh). What shall we discuss?",
        aiWelcomeNoDevices: "No devices added yet. I can analyze your energy once you add a device from the left panel.",
        aiWelcomeDevices: "Your home has {n} devices, totaling {kwh} kWh/mo, ₺{cost}/mo estimated. What would you like to know?",
        aiWelcomeDevicesNoCost: "{n} devices added. I'll give more details once energy calculations complete. What would you like to ask?",
        openAiAssistant: "Open KWhane AI assistant",
        askSomething: "Ask something… (press Enter to send)",
        stopMic: "Stop microphone",
        voiceInput: "Voice input",
        poweredBy: "Powered by Llama 3.2 (Ollama)",
        aiConnectionError: "Couldn't connect to AI service. Make sure the backend is running and OPENAI_API_KEY is set.",
        account: "Account",
        accountDesc: "Account info and danger zone.",
        emailLabel: "Email",
        profileLoadError: "Profile couldn't be loaded.",
        saveFailed: "Save failed",
        savingText: "Saving...",
        savedText: "Saved!",
        dangerZone: "Danger Zone",
        dangerZoneDesc: "All room and device data will be deleted. This action cannot be undone.",
        resetHomeData: "Reset all home data",
        yesDelete: "Yes, delete",
        resetFailed: "Reset failed",
        mlConnectionFailed: "ML connection failed",
        calculating: "Calculating…",
        vatRate: "VAT",
        fillTariffTable: "No tariff data found. Please populate the electricity_tariffs table in Supabase.",

        // ── Calibration Card ───────────────────────────────────
        calibrating: "Calibrating predictions…",
        predictionsMatch: "Predictions match your bill",
        predictionsWithin: "The average of your last {n} bills ({actual} kWh) is within 5% of our prediction ({predicted} kWh).",
        predictionsVsBill: "Predictions vs Bill",
        predVsBillStat: "Over the last {n} bills, actual consumption was {actual} kWh and our prediction was {predicted} kWh",
        addHourDeviceHint: "Once you add an hour-based device like lighting or AC, we can show calibration suggestions here.",
        calibrationSaveFailed: "Could not save calibration.",
        calibrationUpdated: "{name}: updated from {from}h to {to}h.",
        predictionCalibration: "Prediction Calibration",
        calSentence1: "Over the last {n} bills, our predictions averaged",
        calSentence2: "({actual} kWh actual vs {predicted} kWh predicted).",
        calSuggestIncrease: "We can bring predictions closer to your bill by slightly increasing your declared hours.",
        calSuggestDecrease: "We can bring predictions closer to your bill by slightly decreasing your declared hours.",
        hDay: "h/day",
        applied: "Applied",
        applying: "Applying…",
        apply: "Apply",
        calDisclaimer: "No changes are made without your approval. Your original values are always preserved.",

        // ── Bill Entry Modal ───────────────────────────────────
        billSaved: "Bill Saved",
        addBillTitle: "Add Bill",
        billEntryDesc: "Enter your latest electricity bill. This lets us give recommendations based on your real consumption instead of predictions.",
        periodStart: "Period Start",
        periodEnd: "Period End",
        totalConsumption: "Total Consumption",
        totalAmount: "Total Amount",
        providerLabel: "Provider",
        optional: "optional",
        avgUnitPrice: "Average unit price",
        duplicateBill: "A bill for this period already exists.",
        billSaveFailed: "Could not save the bill. Please try again.",

        // ── Bill Diagnostic Card ───────────────────────────────
        analyzingBill: "Analyzing your bill…",
        billSavedNoAnalysis: "Bill saved, but analysis is currently unavailable.",
        ensureMlRunning: "Make sure the ML service is running.",
        billAnalysis: "Bill Analysis",
        matchesPrediction: "Matches prediction",
        higherThanPred: "{pct}% higher than predicted",
        lowerThanPred: "{pct}% lower than predicted",
        consumptionBreakdown: "Consumption Breakdown",
        total: "Total",
        findings: "Our Findings",
        noDevicesAnalyzed: "No devices analyzed yet.",
        noDevicesAnalyzedDesc: "Once you add devices and energy calculations are complete, we can generate a detailed analysis for this bill.",
        ok: "OK",
        addThisDevice: "Add this device",
        updateHours: "Update hours",
        updateYear: "Update year",
        verifyClass: "Verify class",
        updateTariff: "Update tariff",
        hoursUpdatedTo: "Usage hours updated to {h} hours.",
        yearUpdatedTo: "Device year updated to {y}. You can also edit the correct year from the Devices tab.",
        addFromCatalog: "Add from the device catalog: left panel → Add Device.",
        verifyClassHint: "Review the efficiency class from the Devices tab.",
        tariffOverrideSoon: "Tariff override is coming soon — predictions are informational for now.",
        actionFailed: "Action failed.",
    },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(() => {
        return localStorage.getItem("kwhane-lang") || "tr";
    });

    const t = useCallback((key, fallback) => translations[lang]?.[key] || fallback || key, [lang]);

    const toggleLanguage = useCallback(() => {
        const newLang = lang === "tr" ? "en" : "tr";
        setLang(newLang);
        localStorage.setItem("kwhane-lang", newLang);
    }, [lang]);

    return (
        <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
    return context;
};
